# Generated by Django 3.1.4 on 2021-04-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('management', 'Management'), ('employee', 'Employee')], default='management', max_length=20),
            preserve_default=False,
        ),
    ]
