# Generated by Django 3.1.4 on 2021-04-27 09:53

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210427_1127'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('all_clients', django.db.models.manager.Manager()),
            ],
        ),
    ]
